# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: ubuntu-latest

variables:
- name: 'appType'
  value: 'webApp'

steps:
- task: NodeTool@0
  inputs:
    versionSource: 'spec'
    versionSpec: '16.14.0'

- task: Npm@1
  inputs:
    command: 'custom'
    customCommand: 'install --force'

- task: AngularCLI@1
  inputs:
    command: 'build'
    prod: false
    DisableAnalytics: false

- task: CopyFiles@2
  inputs:
    SourceFolder: '$(Build.SourcesDirectory)/dist'
    Contents: '**'
    TargetFolder: '$(Build.ArtifactStagingDirectory)'

- task: AzureRmWebAppDeployment@4
  inputs:
    ConnectionType: 'AzureRM'
    azureSubscription: '$(AZURE_SVC)'
    appType: $(appType)
    WebAppName: 'demo-angular-session-yaml'
    packageForLinux: '$(Build.ArtifactStagingDirectory)'
