# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

resources:
  repositories:
    - repository: templates
      type: github
      name: Premsai2992000/pipeline-template
      endpoint: sampe-github-svc

trigger:
- master

pool:
  vmImage: ubuntu-latest

stages: 
- stage: Build
  displayName: Build an angular application
  jobs:
    - job: Build
      steps:
       - template: steps/ng-build.yml@templates
         parameters:
            versionSpec: '16.14.0'
 
- stage: Deploy
  displayName: Deploy
  jobs:
  - deployment: Deploy
    environment: deploy
    strategy: 
     runOnce:
       deploy:
         steps:
          - template: steps/ng-deploy.yml@templates